export interface BrawlerConfig {
  id: string;
  name: string;
  health: number;
  speed: number;
  attackDamage: number;
  attackRange: number;
  attackCooldown: number;
  maxAmmo: number;
  reloadSpeed: number;
  projectileSpeed: number;
  superName: string;
  description: string;
  color: string;
}

export const BRAWLERS: Record<string, BrawlerConfig> = {
  shellie: {
    id: "shellie",
    name: "Shellie",
    health: 3600,
    speed: 0.15,
    attackDamage: 300,
    attackRange: 7,
    attackCooldown: 500,
    maxAmmo: 3,
    reloadSpeed: 1500,
    projectileSpeed: 0.4,
    superName: "Super Shell",
    description: "Spread-fire shotgun brawler.",
    color: "#ff00ff"
  },
  bolt: {
    id: "bolt",
    name: "Bolt",
    health: 2800,
    speed: 0.16,
    attackDamage: 320,
    attackRange: 9,
    attackCooldown: 200,
    maxAmmo: 3,
    reloadSpeed: 1600,
    projectileSpeed: 0.6,
    superName: "Bullet Storm",
    description: "Dual wielding long range sharpshooter.",
    color: "#ff0000"
  },
  bill: {
    id: "bill",
    name: "Bill",
    health: 5000,
    speed: 0.14,
    attackDamage: 400,
    attackRange: 5,
    attackCooldown: 400,
    maxAmmo: 3,
    reloadSpeed: 1800,
    projectileSpeed: 0.35,
    superName: "Stampede",
    description: "Short range tank with a shotgun.",
    color: "#0000ff"
  },
  nina: {
    id: "nina",
    name: "Nina",
    health: 3800,
    speed: 0.15,
    attackDamage: 800,
    attackRange: 6,
    attackCooldown: 600,
    maxAmmo: 3,
    reloadSpeed: 1200,
    projectileSpeed: 0.4,
    superName: "Big Bear",
    description: "Summons a bear to fight.",
    color: "#8b4513"
  },
  brack: {
    id: "brack",
    name: "Brack",
    health: 2400,
    speed: 0.15,
    attackDamage: 1100,
    attackRange: 10,
    attackCooldown: 1000,
    maxAmmo: 3,
    reloadSpeed: 2100,
    projectileSpeed: 0.3,
    superName: "Rocket Rain",
    description: "Fires long-range rockets.",
    color: "#ff8c00"
  },
  el_primero: {
    id: "el_primero",
    name: "El Primero",
    health: 6000,
    speed: 0.16,
    attackDamage: 360,
    attackRange: 3,
    attackCooldown: 200,
    maxAmmo: 3,
    reloadSpeed: 800,
    projectileSpeed: 0.5,
    superName: "Flying Leap",
    description: "Melee wrestler.",
    color: "#00008b"
  },
  barnaby: {
    id: "barnaby",
    name: "Barnaby",
    health: 2400,
    speed: 0.15,
    attackDamage: 600,
    attackRange: 7,
    attackCooldown: 800,
    maxAmmo: 3,
    reloadSpeed: 2000,
    projectileSpeed: 0.3,
    superName: "Last Call",
    description: "Throws bottles of fire.",
    color: "#ffd700"
  },
  loco: {
    id: "loco",
    name: "Loco",
    health: 4000,
    speed: 0.15,
    attackDamage: 700,
    attackRange: 7,
    attackCooldown: 600,
    maxAmmo: 3,
    reloadSpeed: 1600,
    projectileSpeed: 0.4,
    superName: "Encore",
    description: "Heals teammates with music.",
    color: "#ffff00"
  },
  rose: {
    id: "rose",
    name: "Rose",
    health: 5400,
    speed: 0.16,
    attackDamage: 460,
    attackRange: 3.5,
    attackCooldown: 300,
    maxAmmo: 3,
    reloadSpeed: 1000,
    projectileSpeed: 0.4,
    superName: "Thorny Shield",
    description: "Shielded melee brawler.",
    color: "#32cd32"
  },
  jessa: {
    id: "jessa",
    name: "Jessa",
    health: 3000,
    speed: 0.15,
    attackDamage: 840,
    attackRange: 9,
    attackCooldown: 800,
    maxAmmo: 3,
    reloadSpeed: 1800,
    projectileSpeed: 0.4,
    superName: "Scrappy",
    description: "Fires energy orbs that bounce.",
    color: "#ffa500"
  },
  mikey: {
    id: "mikey",
    name: "Mikey",
    health: 2800,
    speed: 0.15,
    attackDamage: 800,
    attackRange: 7,
    attackCooldown: 1000,
    maxAmmo: 3,
    reloadSpeed: 1700,
    projectileSpeed: 0.35,
    superName: "Big Barrel",
    description: "Throws dynamite.",
    color: "#ff0000"
  },
  tock: {
    id: "tock",
    name: "Tock",
    health: 2200,
    speed: 0.15,
    attackDamage: 640,
    attackRange: 9,
    attackCooldown: 500,
    maxAmmo: 3,
    reloadSpeed: 2200,
    projectileSpeed: 0.4,
    superName: "Head First",
    description: "Minesweeper robot.",
    color: "#a9a9a9"
  },
  sixteen_bit: {
    id: "sixteen_bit",
    name: "16-Bit",
    health: 4800,
    speed: 0.12,
    attackDamage: 320,
    attackRange: 10,
    attackCooldown: 200,
    maxAmmo: 3,
    reloadSpeed: 1500,
    projectileSpeed: 0.5,
    superName: "Damage Booster",
    description: "High damage slow robot.",
    color: "#4682b4"
  },
  amy: {
    id: "amy",
    name: "Amy",
    health: 3600,
    speed: 0.15,
    attackDamage: 500,
    attackRange: 7,
    attackCooldown: 600,
    maxAmmo: 3,
    reloadSpeed: 2000,
    projectileSpeed: 0.4,
    superName: "Haters Gonna Hate",
    description: "Spray-based area control.",
    color: "#ee82ee"
  },
  stun: {
    id: "stun",
    name: "Stun",
    health: 2800,
    speed: 0.16,
    attackDamage: 580,
    attackRange: 7.5,
    attackCooldown: 400,
    maxAmmo: 3,
    reloadSpeed: 1500,
    projectileSpeed: 0.5,
    superName: "Nitro Boost",
    description: "Dashing stunt driver.",
    color: "#000000"
  },
  pippa: {
    id: "pippa",
    name: "Pippa",
    health: 2400,
    speed: 0.15,
    attackDamage: 1520,
    attackRange: 10,
    attackCooldown: 1500,
    maxAmmo: 3,
    reloadSpeed: 2300,
    projectileSpeed: 0.8,
    superName: "Poppin",
    description: "Long range sniper.",
    color: "#add8e6"
  },
  pama: {
    id: "pama",
    name: "Pama",
    health: 4800,
    speed: 0.15,
    attackDamage: 260,
    attackRange: 9,
    attackCooldown: 100,
    maxAmmo: 3,
    reloadSpeed: 1300,
    projectileSpeed: 0.5,
    superName: "Mama Squeeze",
    description: "Healer scrap shooter.",
    color: "#ff1493"
  },
  tank: {
    id: "tank",
    name: "Tank",
    health: 7000,
    speed: 0.15,
    attackDamage: 1200,
    attackRange: 6,
    attackCooldown: 1200,
    maxAmmo: 3,
    reloadSpeed: 1400,
    projectileSpeed: 0.4,
    superName: "Stunning Shock",
    description: "Hammer-wielding giant.",
    color: "#4b0082"
  },
  bebe: {
    id: "bebe",
    name: "Bebe",
    health: 4200,
    speed: 0.16,
    attackDamage: 1300,
    attackRange: 3.5,
    attackCooldown: 800,
    maxAmmo: 3,
    reloadSpeed: 800,
    projectileSpeed: 0.4,
    superName: "Spitball",
    description: "Bat-wielding brawler.",
    color: "#00ced1"
  },
  bee: {
    id: "bee",
    name: "Bee",
    health: 2400,
    speed: 0.15,
    attackDamage: 800,
    attackRange: 10,
    attackCooldown: 500,
    maxAmmo: 1,
    reloadSpeed: 1000,
    projectileSpeed: 0.6,
    superName: "Iron Swarm",
    description: "Single shot sniper.",
    color: "#f5deb3"
  }
};
